arch:
  - amd64
  - ppc64le
language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
# Only send notifications on new failures
notifications:
  email:
    on_success: never
    on_failure: change
# command to install dependencies
install:
  - pip install -r test_requirements.txt
# command to run tests
script:
  - pytest
  - pycodestyle fortls --max-line-length=120 --ignore=E226,E722,W503
  - pyflakes fortls
